version: '3'
services:
  app:
    build:
      context: .
      args:
        - BASE_URL=${BASE_URL}
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - "APP_PORT=${APP_PORT}"
      - "BASE_URL=${BASE_URL}"